### ISSUE TITLE
请问onnx->tensrort 支持动态batch吗？  

### ISSUE THREAD

**Issue by wangjingg** [heroinlin/SlowFastTRT#2]
如何使用动态btach进行tensorrt推理

**Comment by heroinlin** [comment]
> 如何使用动态btach进行tensorrt推理

我这边没有做动态batch的推理，在tensorrt的engine中有个max_batch_size参数设置， 你可以从这个角度试试。
也可以看看这个地址的介绍  https://zhuanlan.zhihu.com/p/387853124， 后续我有时间也会尝试进行更新。

**Comment by heroinlin** [comment]
@wangjingg  动态batchsize支持已添加！ 细节请查看提交[b2665fa](https://github.com/heroinlin/SlowFastTRT/commit/b2665fa87b595df997389f7dbf3aeb6b354e5b42)
