### ISSUE TITLE
ONNX conversion for model trained on AVA

### ISSUE THREAD

**Issue by namng-uwu** [heroinlin/SlowFastTRT#3]
Hi, Thanks for sharing your repo. As far as I see, your convert script works well on model trained with Kinetics dataset but I'm looking for a way to convert SlowFast model trained on AVA which is a spatial-temporal action detection dataset but I don't see anyone doing this. How should I modify your script to do it? Thank you~

**Comment by heroinlin** [comment]
maybe you can try to modify this way:
inputs = [slow_pathway, fast_pathway]  >> inputs = [slow_pathway, fast_pathway, bboxes], where bboxes is a tensor and size is [-1, -1, 5], for example bboxes = torch. as_tensor([[[0, 128.35, 73.7, 155.2, 129.7], [0, 150.35, 50.7, 185.2, 141.2]]]), default to set boxes num is 2.

**Comment by ljl02521** [comment]
@namKolorfuL Did you convert successfully for Slowfast on AVA?

**Comment by dongxiaolong** [comment]
> 

I also want to convert the model. Do you convert it successfully ?

**Comment by namng-uwu** [comment]
> @namKolorfuL Did you convert successfully for Slowfast on AVA?

You can try modifying his script, we converted the model to ONNX but the TensorRT one failed due to unsupported layer.

**Comment by ljl02521** [comment]
@namKolorfuL I didn't implement slowfast to tensorrt because some operations are not supported now

**Comment by 1005452649** [comment]
> > @namKolorfuL Did you convert successfully for Slowfast on AVA?
> 
> You can try modifying his script, we converted the model to ONNX but the TensorRT one failed due to unsupported layer.

Did you convert onnx successfully for Slowfast on AVA?

**Comment by heroinlin** [comment]
TensorRT is unsupported to the RoiAlign layer now.  AVA model can't be successfully converted into a TensorRT model. 
![image](https://user-images.githubusercontent.com/17489822/197677301-46b1b756-1b23-4dca-8794-0fba88fb33ed.png)
https://github.com/NVIDIA/TensorRT/pull/2023/commits/61982a80913d523f589f260fdac27348ac8eaa27
